### ISSUE TITLE
Packer Build does not start on CentOS7 and CentOS8

### ISSUE THREAD

**Issue by dwannamaker-onr** [kubernetes-sigs/image-builder#684]
Two different CentOS systems had this issue in our lab:  Trying to build the windows image with Packer, targeting a vCenter host cluster.  No logs our output from Packer, no tasks happening in vCenter.  SELINUX is disabled, Firewall is disabled.  Running as root.

Here's the output:
```
[root@docker-vm capi]#  PACKER_LOG=1 PACKER_LOG_PATH="packer.log" PACKER_FLAGS='-force -on-error=ask -debug' PACKER_VAR_FILES=packer/ova/windows.json no_proxy=* make build-node-ova-vsphere-windows-2019
vsphere-windows-2019
hack/ensure-ansible.sh
hack/ensure-ansible-windows.sh
hack/ensure-packer.sh
hack/ensure-goss.sh
Right version of binary present
hack/ensure-ovftool.sh
packer build -var-file="/root/image-builder/images/capi/packer/config/kubernetes.json"  -var-file="/root/image-builder/images/capi/packer/config/windows/kubernetes.json"  -var-file="/root/image-builder/images/capi/packer/config/containerd.json"  -var-file="/root/image-builder/images/capi/packer/config/windows/containerd.json"  -var-file="/root/image-builder/images/capi/packer/config/windows/docker.json"  -var-file="/root/image-builder/images/capi/packer/config/windows/ansible-args-windows.json"  -var-file="/root/image-builder/images/capi/packer/config/windows/common.json"  -var-file="/root/image-builder/images/capi/packer/config/windows/cloudbase-init.json"  -var-file="/root/image-builder/images/capi/packer/config/goss-args.json"  -var-file="/root/image-builder/images/capi/packer/config/additional_components.json"  -force -on-error=ask -debug -color=true  -var-file="packer/ova/packer-common.json" -var-file="/root/image-builder/images/capi/packer/ova/windows-2019.json" -var-file="packer/ova/vsphere.json" -except=esx -except=local -only=vsphere-iso -var-file="/root/image-builder/images/capi/packer/ova/windows.json"  -only=vsphere packer/ova/packer-windows.json
```
(no output after this point, waited overnight.. also nothing in packer.log)

Here's my windows.json:
```
{
    "windows_updates_categories": "",
    "windows_updates_kbs": "",
    "kubernetes_semver": "v1.20.5",
    "cluster": "ALN-Cluster",
    "template": "",
    "password": "<removed>",
    "folder": "",
    "runtime": "containerd",
    "username": "administrator@vsphere.local",
    "datastore": "archive01",
    "datacenter": "ALN",
    "convert_to_template": "true",
    "vmtools_iso_path": "[archive01] iso/VMware-tools-windows-11.2.5-17337674.iso",
    "insecure_connection": "true",
    "disable_hypervisor": "false",
    "network": "ALN-VLAN103",
    "linked_clone": "false",
    "os_iso_path": "[archive01] iso/en_windows_server_2019_updated_august_2021_x64_dvd.iso",
    "resource_pool": "",
    "vcenter_server": "10.10.105.98",
    "create_snapshot": "false",
    "netbios_host_name_compatibility": "false",
    "kubernetes_base_url": "http://10.10.115.103:3000/kubernetes/v1.20.5+vmware.2/bin/windows/amd64/",
    "containerd_url": "http://10.10.115.103:3000/containerd/cri-containerd-v1.4.6+vmware.1.windows-amd64.tar",
    "containerd_sha256_windows": "af8f2271bd84a6077e38308861ce76bd2647b31e1b985943bddcde433067c9f5",
    "pause_image": "mcr.microsoft.com/oss/kubernetes/pause:1.3.0",
    "prepull": "false",
    "additional_prepull_images": "",
    "additional_download_files": "https://raw.githubusercontent.com/vmware-tanzu/antrea/v0.13.1/hack/windows/Helper.psm1"
}
```

Things I checked:
- Added -debug, and PACKER_LOG options
- Reachability / Resolvability to vCenter from my build VM verified
- Credentials / Access within vCenter verified
- CentOS Updates (applied latest)

Steps taken on CentOS:
1. Yum update (all/latest)
2. yum install python3 git make -y
3. git clone https://github.com/kubernetes-sigs/image-builder
4. cd image-builder/images/capi
5. make deps-ova

```
[root@centos8 capi]# make deps-ova
hack/ensure-ansible.sh
WARNING: Running pip install with root privileges is generally not a good idea.                          Try `pip3 install --user` instead.
Collecting ansible==2.10.0
  Downloading https://files.pythonhosted.org/packages/4a/0b/44b586965bd51135d391                         5a02d1327fb392843630435cd41d6c89898c5f24/ansible-2.10.0.tar.gz (25.5MB)
    100% |████████████████████████████████| 25.5MB 57kB/s
Collecting ansible-base<2.11,>=2.10.1 (from ansible==2.10.0)
  Downloading https://files.pythonhosted.org/packages/53/a1/4969026019364c9a03ac                         276e89d7ea0b398f7d4b5c33771d36fc7808550f/ansible-base-2.10.13.tar.gz (6.0MB)
    100% |████████████████████████████████| 6.0MB 249kB/s
Collecting jinja2 (from ansible-base<2.11,>=2.10.1->ansible==2.10.0)
  Downloading https://files.pythonhosted.org/packages/80/21/ae597efc7ed8caaa43fb                         35062288baaf99a7d43ff0cf66452ddf47604ee6/Jinja2-3.0.1-py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 8.5MB/s
Requirement already satisfied: PyYAML in /usr/lib64/python3.6/site-packages (fro                         m ansible-base<2.11,>=2.10.1->ansible==2.10.0)
Collecting cryptography (from ansible-base<2.11,>=2.10.1->ansible==2.10.0)
  Downloading https://files.pythonhosted.org/packages/cc/98/8a258ab4787e6f835d35                         0639792527d2eb7946ff9fc0caca9c3f4cf5dcfe/cryptography-3.4.8.tar.gz (546kB)
    100% |████████████████████████████████| 552kB 2.5MB/s
    Complete output from command python setup.py egg_info:

            =============================DEBUG ASSISTANCE=======================                         ===
            If you are seeing an error here please try the following to
            successfully install cryptography:

            Upgrade to the latest pip and try again. This will fix errors for mo                         st
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE=======================                         ===

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-k21bz2hw/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-k2                         1bz2hw/cryptography/
make: *** [Makefile:86: deps-ova] Error 1
```
6. Upgrade pip with pip3 install --upgrade pip
7. Rerun make deps-ova
(continues)
```
Collecting cryptography
  Downloading cryptography-3.4.8-cp36-abi3-manylinux_2_24_x86_64.whl (3.0 MB)
     |████████████████████████████████| 3.0 MB 1.5 MB/s
Collecting packaging
  Downloading packaging-21.0-py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 8.7 MB/s
Collecting cffi>=1.12
  Downloading cffi-1.14.6-cp36-cp36m-manylinux1_x86_64.whl (401 kB)
     |████████████████████████████████| 401 kB 34.5 MB/s
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
     |████████████████████████████████| 112 kB 45.6 MB/s
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.0.1-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (30 kB)
Collecting pyparsing>=2.0.2
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 14.1 MB/s
Using legacy 'setup.py install' for ansible, since package 'wheel' is not installed.
Using legacy 'setup.py install' for ansible-base, since package 'wheel' is not installed.
Installing collected packages: pycparser, pyparsing, MarkupSafe, cffi, packaging, jinja2, cryptography, ansible-base, ansible
    Running setup.py install for ansible-base ... done
    Running setup.py install for ansible ... done
Successfully installed MarkupSafe-2.0.1 ansible-2.10.0 ansible-base-2.10.13 cffi-1.14.6 cryptography-3.4.8 jinja2-3.0.1 packaging-21.0 pycparser-2.20 pyparsing-2.4.7
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
User's Python3 binary directory must be in $PATH
Location of package is:
Location: /root/.local/lib/python3.6/site-packages
$PATH is currently: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
make: *** [Makefile:86: deps-ova] Error 1
```
8. Add .local/bin to path:  export PATH=$PATH:/root/.local/bin
9. Rerun make deps-ova
(continued)
```
hack/ensure-ansible-windows.sh
Collecting pywinrm==0.4.2
  Downloading pywinrm-0.4.2-py2.py3-none-any.whl (44 kB)
     |████████████████████████████████| 44 kB 1.1 MB/s
Collecting requests-ntlm>=0.3.0
  Downloading requests_ntlm-1.1.0-py2.py3-none-any.whl (5.7 kB)
Collecting xmltodict
  Downloading xmltodict-0.12.0-py2.py3-none-any.whl (9.2 kB)
Requirement already satisfied: six in /usr/lib/python3.6/site-packages (from pywinrm==0.4.2) (1.11.0)
Collecting requests>=2.9.1
  Downloading requests-2.26.0-py2.py3-none-any.whl (62 kB)
     |████████████████████████████████| 62 kB 2.0 MB/s
Collecting idna<4,>=2.5
  Downloading idna-3.2-py3-none-any.whl (59 kB)
     |████████████████████████████████| 59 kB 7.1 MB/s
Collecting charset-normalizer~=2.0.0
  Downloading charset_normalizer-2.0.4-py3-none-any.whl (36 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
     |████████████████████████████████| 145 kB 8.1 MB/s
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.6-py2.py3-none-any.whl (138 kB)
     |████████████████████████████████| 138 kB 31.2 MB/s
Requirement already satisfied: cryptography>=1.3 in /root/.local/lib/python3.6/site-packages (from requests-ntlm>=0.3.0->pywinrm==0.4.2) (3.4.8)
Collecting ntlm-auth>=1.0.2
  Downloading ntlm_auth-1.5.0-py2.py3-none-any.whl (29 kB)
Requirement already satisfied: cffi>=1.12 in /root/.local/lib/python3.6/site-packages (from cryptography>=1.3->requests-ntlm>=0.3.0->pywinrm==0.4.2) (1.14.6)
Requirement already satisfied: pycparser in /root/.local/lib/python3.6/site-packages (from cffi>=1.12->cryptography>=1.3->requests-ntlm>=0.3.0->pywinrm==0.4.2) (2.20)
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests, ntlm-auth, xmltodict, requests-ntlm, pywinrm
Successfully installed certifi-2021.5.30 charset-normalizer-2.0.4 idna-3.2 ntlm-auth-1.5.0 pywinrm-0.4.2 requests-2.26.0 requests-ntlm-1.1.0 urllib3-1.26.6 xmltodict-0.12.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Name: pywinrm
Version: 0.4.2
Summary: Python library for Windows Remote Management
Home-page: http://github.com/diyan/pywinrm/
Author: Alexey Diyan
Author-email: alexey.diyan@gmail.com
License: MIT license
Location: /root/.local/lib/python3.6/site-packages
Requires: six, xmltodict, requests-ntlm, requests
Required-by:
hack/ensure-packer.sh
hack/ensure-goss.sh
/root/.packer.d/plugins/packer-provisioner-goss: OK
hack/ensure-ovftool.sh
[root@centos8 capi]#
```
10. Now that deps complete, run Packer Build and reference the windows.json

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by jayunit100** [comment]
big thanks for filing this .... 

.... @perithompson do you think the fact that `packer build` literally, hangs forever, is a bug on the packer side that we should track in this issue ?

I do, at the very least, so others can see this image as a reference.

**Comment by dwannamaker-onr** [comment]
Hey I, I don't know if this helps, but when I press <Enter> while waiting for packer, I get this output from the console:

```
skipping line: 1

skipping line: 2

skipping line: 3

skipping line: 4

skipping line: 5
```

**Comment by perithompson** [comment]
Thanks @jayunit100, someone else mentioned this to me the other day but I think this is a packer issue and not image-builder, the only question mark is whether it is something to do with how the ensure scripts configures packer

**Comment by perithompson** [comment]
I saw https://github.com/hashicorp/packer/issues/5113 and wondered if this was the same issue but the other person seeing this hasn't got past the error yet either

@dwannamaker-onr  could you use the docker image instead of installing all the pre-reqs to unblock you? https://github.com/kubernetes-sigs/image-builder/blob/master/docs/book/src/capi/container-image.md

**Comment by dwannamaker-onr** [comment]
@perithompson Thanks.  I was able to get past being stuck by just using an Ubuntu VM.  I think Docker would have worked also since it's using Ubuntu as the base.
